version: '3'

volumes:
  dev_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./config/dev/django/Dockerfile
    image: animehub_dev_django
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  backend:
    <<: *django
    image: animehub_dev_backend
    ports:
      - 8000:8000
    command: ./manage.py runserver 0.0.0.0:8000

  nuxt:
    build:
      context: .
      dockerfile: ./config/dev/nuxt/Dockerfile
    image: animehub_dev_nuxt
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    command: yarn dev

  postgres:
    image: postgres:10
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:3.2
    ports:
      - 6379:6379

  celeryworker:
    <<: *django
    image: animehub_dev_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: animehub_dev_celerybeat
    command: /start-celerybeat
