# Generated by Django 2.2.4 on 2019-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
