# Generated by Django 2.2.4 on 2019-08-28 17:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_anime_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('tv', 'TV'), ('ova', 'OVA'), ('ona', 'ONA'), ('film', 'Фильм'), ('preview', 'Preview'), ('special', 'Special'), ('open', 'Opening'), ('end', 'Ending'), ('menu', 'Menu'), ('bonus', 'Бонус'), ('other', 'Другой')], max_length=20, null=True, verbose_name='Тип серии')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер серии')),
                ('admin_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['admin_order'],
            },
        ),
        migrations.CreateModel(
            name='VideoSourceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Источник видео',
                'verbose_name_plural': 'Источники видео',
            },
        ),
        migrations.AlterField(
            model_name='anime',
            name='english_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='japanese_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='other_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), blank=True, size=None),
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_link', models.CharField(max_length=1000, null=True, verbose_name='Ссылка')),
                ('team_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название команды')),
                ('people_list', models.CharField(blank=True, max_length=240, null=True, verbose_name='Список людей')),
                ('translation_type', models.CharField(blank=True, choices=[('ru-voice', 'Озвучка'), ('ru-sub', 'Русские субтитры'), ('en-voice', 'Английская озвучка'), ('en-sub', 'Английские субтитры'), ('jp-sub', 'Японские субтитры'), ('raw', 'RAW')], max_length=20, null=True, verbose_name='Тип перевода')),
                ('admin_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.VideoSourceName', verbose_name='Источник')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео файл',
                'verbose_name_plural': 'Видео файлы',
                'ordering': ['admin_order'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Anime'),
        ),
    ]
